name = "promptmarket"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production]

[env.production.vars]
ENVIRONMENT = "production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "db-adigi"
database_id = "779ebfcb-c208-43e4-be81-2269b9d08d63"

[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "aidigi"
