name = "promptmarket"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "db-adigi"
database_id = "779ebfcb-c208-43e4-be81-2269b9d08d63"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "aidigi"

[env.production.vars]
ENVIRONMENT = "production"
